admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

# Gestion des utilisateurs

admin_users:
    path:     /users
    defaults: { _controller: AdminBundle:Default:users }

admin_users_edit:
    path:     /users/edit/{id}
    defaults: { _controller: AdminBundle:Default:usersEdit }

admin_users_ajax_promote:
    path:     /users/ajax/promote
    defaults: { _controller: AdminBundle:Default:ajaxUserPromote }

admin_users_ajax_delete:
    path:     /users/ajax/delete
    defaults: { _controller: AdminBundle:Default:ajaxUserDelete }

# Gestion des news

admin_news:
    path:     /news
    defaults: { _controller: AdminBundle:Default:news }

admin_news_ajax_get:
    path:     /news/ajax/get
    defaults: { _controller: AdminBundle:Default:ajaxNewsGet }

admin_news_ajax_add:
    path:     /news/ajax/add
    defaults: { _controller: AdminBundle:Default:ajaxNewsAdd }

admin_news_ajax_edit:
    path:     /news/ajax/edit
    defaults: { _controller: AdminBundle:Default:ajaxNewsEdit }

admin_news_ajax_delete:
    path:     /news/ajax/delete
    defaults: { _controller: AdminBundle:Default:ajaxNewsDelete }
