main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
