<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    function getAll() {
        $query = $this->createQueryBuilder('c')
            ->select('s')
            ->from('AdminBundle:Config', 's', 's.name');
        
        $result = $query->getQuery()->getResult();

        return $result;
    }
}
