<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getTeam( $id ) {
        $em = $this->getEntityManager();

        $team = $em->getRepository( 'TeamBundle:Team' )->findOneByManager( $id );

        return $team;
    }
}
