team_homepage:
    path:     /
    defaults: { _controller: TeamBundle:Team:index }

team_registration:
    path:     /registration
    defaults: { _controller: TeamBundle:Team:registration }

team_player_ajax_add:
    path:     /player/ajax/add
    defaults: { _controller: TeamBundle:Player:ajaxAdd }

team_player_ajax_delete:
    path:     /player/ajax/delete
    defaults: { _controller: TeamBundle:Player:ajaxDelete }

team_player_ajax_get:
    path:     /player/ajax/get
    defaults: { _controller: TeamBundle:Player:ajaxGet }

team_ajax_setregistered:
    path:     /ajax/setregistered
    defaults: { _controller: TeamBundle:Team:ajaxSetRegistered }


# Front

team_front_homepage:
    path:     /view/{id}-{team}
    defaults: { _controller: TeamBundle:Team:frontIndex, id:"", team:"" }

