match_results:
    path:     /{id}
    defaults: { _controller: "MatchBundle:Match:results" }
    requirements:
        id:  \d+

match_calendar:
    path:     /calendar
    defaults: { _controller: "MatchBundle:Match:calendar" }

match_ajax_get:
    path:     /ajax/get
    defaults: { _controller: "MatchBundle:Match:ajaxGet" }

match_ajax_updateprestations:
    path:     /ajax/updateprestations
    defaults: { _controller: "MatchBundle:Match:ajaxUpdatePrestations" }

match_referee:
    path:     /referee
    defaults: { _controller: "MatchBundle:Referee:index" }
