match_results:
    path:     /{id}
    defaults: { _controller: "MatchBundle:Match:results" }
    requirements:
        id:  \d+

match_calendar:
    path:     /calendar
    defaults: { _controller: "MatchBundle:Match:calendar" }
