main_homepage:
    path:     /
    defaults: { _controller: "MainBundle:Default:index" }

ladder:
    path:     /classement
    defaults: { _controller: "MainBundle:Default:ladder" }

calendar:
    path:     /calendrier
    defaults: { _controller: "MainBundle:Default:calendar" }
